export const coachesData = [
  {
    id: "ariel",
    name: "Ariel Okal",
    title: "BASKETBALL COACH",
    image: "/src/assets/ariel-okal.jpg",
    aboutTitle: "About Arial",
    aboutText: "Introducing Arial Okal, a basketball dynamo with unmatched speed and agility on the court. His coaching style revolves around refining footwork and enhancing agility. Follow for tips and insights on boosting your speed and agility game.",
    quote: "Speed defines the pace, agility conquers the game.",
    section1Title: "SPEED DYNAMO",
    strength: "Speed & Agile Court Moves",
    expertise: "Lightning-fast speed, agile maneuvers",
    section2Title: "AGILE MOVEMENT EXPERT",
    coachingFocus: "Enhancing footwork, boosting agility",
    mainFocus: ["Speed enhancement tips", "Agility training insights"],
    tacticsTitle: "Tactics",
    tacticsText: "Footwork Finesse: Elevate your game by mastering swift and precise foot movements.",
    trainingTitle: "TRAINING POSITIONS",
    trainingMainFocus: ["Guards", "Fast-paced offense players", "Players focusing on agility"],
    also: "Trains all basketball Positions"
  },
  {
    id: "albert",
    name: "Albert Odero",
    title: "BASKETBALL COACH",
    image: "/src/assets/albert-odero.jpg",
    aboutTitle: "About Albert",
    aboutText: "Get to know Albert Odero, a basketball virtuoso in shooting accuracy and flawless ball handling. His coaching aims to perfect shooting techniques and elevate ball control skills. Follow for exclusive tutorials and drills to boost your game.",
    quote: "Precision in every shot, mastery in every move.",
    section1Title: "BALL CONTROL MAESTRO",
    strength: "Shooting Accuracy & Ball Handling",
    expertise: "Precise shooting, impeccable ball control",
    section2Title: "PRECISION TRAINING INSIGHTS",
    coachingFocus: "Fine-tuning shooting techniques, mastering ball handling",
    mainFocus: ["Shooting drills", "Ball control tutorials"],
    tacticsTitle: "Tactics",
    tacticsText: "Ball Handling Mastery: Achieve seamless control through precise drills and technique.",
    trainingTitle: "TRAINING POSITIONS",
    trainingMainFocus: ["Shooting guards", "Power forwards", "Ball handlers"],
    also: "Trains all basketball Positions"
  },
  {
    id: "ken",
    name: "Ken Wachira",
    title: "BASKETBALL COACH",
    image: "/src/assets/ken-wachira.jpg",
    aboutTitle: "About Ken",
    aboutText: "Meet Ken Wachira, a basketball strategist known for his quick decision-making and game-reading abilities. His coaching style emphasizes enhancing court vision and predicting opponents' moves. Gain exclusive insights into basketball tactics and honing your 3-point game with Ken Wachira, the maestro behind the arc.",
    quote: "Read the game, own the court.",
    section1Title: "DECISIVE MOVES SPECIALIST",
    strength: "Strategic Vision & Quick Decision-Making & 3-Point Shooting",
    expertise: "Reading the game, making decisive moves, excellent 3-point shooting.",
    section2Title: "VISIONARY INSIGHTS",
    coachingFocus: "Improving court vision, anticipating opponent moves",
    mainFocus: ["Tactical Insights", "Rapid decision-making drills"],
    trainingTitle: "TRAINING POSITIONS",
    trainingMainFocus: ["Point guards", "Small forwards", "Team strategists"],
    also: "Trains all basketball Positions",
    accoladesTitle: "ACCOLADES",
    accoladesText: "MVP 2022, renowned for exceptional 3-point shooting skills."
  }
];